#!/bin/bash

wget -c http://cn.archive.ubuntu.com/ubuntu/pool/main/g/gcc-10/gcc-10-base_10.2.0-13ubuntu1_amd64.deb
dpkg -i *.deb
rm *.deb

wget -c http://cn.archive.ubuntu.com/ubuntu/pool/main/g/gcc-10/libgcc-s1_10.2.0-13ubuntu1_amd64.deb
dpkg -i *.deb
rm *.deb

wget -c http://cn.archive.ubuntu.com/ubuntu/pool/main/g/gcc-10/libstdc++6_10.2.0-13ubuntu1_amd64.deb
dpkg -i *.deb
rm *.deb

wget -c http://cn.archive.ubuntu.com/ubuntu/pool/main/p/protobuf/libprotobuf-lite17_3.6.1.3-2ubuntu5_amd64.deb
dpkg -i *.deb
rm *.deb

wget -c http://cn.archive.ubuntu.com/ubuntu/pool/main/z/zlib/zlib1g_1.2.11.dfsg-2ubuntu1.2_amd64.deb
dpkg -i *.deb
rm *.deb

wget -c http://cn.archive.ubuntu.com/ubuntu/pool/main/z/zlib/zlib1g-dev_1.2.11.dfsg-2ubuntu1.2_amd64.deb
dpkg -i *.deb
rm *.deb

wget -c http://cn.archive.ubuntu.com/ubuntu/pool/main/p/protobuf/libprotobuf17_3.6.1.3-2ubuntu5_amd64.deb
dpkg -i *.deb
rm *.deb

wget -c http://cn.archive.ubuntu.com/ubuntu/pool/main/p/protobuf/libprotobuf-dev_3.6.1.3-2ubuntu5_amd64.deb
dpkg -i *.deb
rm *.deb

wget -c http://cn.archive.ubuntu.com/ubuntu/pool/main/p/protobuf/libprotoc17_3.6.1.3-2ubuntu5_amd64.deb
dpkg -i *.deb
rm *.deb

wget -c http://cn.archive.ubuntu.com/ubuntu/pool/universe/p/protobuf/protobuf-compiler_3.6.1.3-2ubuntu5_amd64.deb
dpkg -i *.deb
rm *.deb

wget -c http://cn.archive.ubuntu.com/ubuntu/pool/main/p/protobuf/libprotoc-dev_3.6.1.3-2ubuntu5_amd64.deb
dpkg -i *.deb
rm *.deb

wget -c http://cn.archive.ubuntu.com/ubuntu/pool/universe/n/nlohmann-json3/nlohmann-json3-dev_3.7.3-1_all.deb
dpkg -i *.deb
rm *.deb


wget -c https://dorahand.dorabot.org/binary_blob/libdorahand-dev_1.1.13-0ubuntu1-amd64.deb
dpkg -i *.deb
rm *.deb